# Generated by Django 5.2.7 on 2025-10-21 18:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Malzeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benzersiz_id', models.CharField(db_index=True, editable=False, max_length=255, unique=True)),
                ('seri_no', models.CharField(blank=True, db_index=True, default='YOK', max_length=100, null=True)),
                ('malzeme_kodu', models.CharField(max_length=100)),
                ('parti_no', models.CharField(blank=True, default='YOK', max_length=100, null=True)),
                ('lokasyon_kodu', models.CharField(default='YOK', max_length=100)),
                ('renk', models.CharField(blank=True, default='YOK', max_length=50, null=True)),
                ('depo_adi', models.CharField(blank=True, max_length=100, null=True)),
                ('stok_grup', models.CharField(blank=True, max_length=100, null=True)),
                ('depo_sinif', models.CharField(blank=True, max_length=100, null=True)),
                ('malzeme_adi', models.CharField(max_length=255)),
                ('barkod', models.CharField(blank=True, max_length=100, null=True)),
                ('olcu_birimi', models.CharField(max_length=20)),
                ('sistem_stogu', models.FloatField(default=0.0)),
                ('sistem_tutari', models.FloatField(default=0.0)),
                ('birim_fiyat', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Malzeme',
                'verbose_name_plural': 'Malzemeler',
            },
        ),
        migrations.CreateModel(
            name='SayimEmri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255, verbose_name='Sayım Emri Adı')),
                ('tarih', models.DateTimeField(default=django.utils.timezone.now)),
                ('durum', models.CharField(choices=[('Açık', 'Açık'), ('Tamamlandı', 'Tamamlandı')], default='Açık', max_length=20)),
                ('onay_tarihi', models.DateTimeField(blank=True, null=True)),
                ('atanan_personel', models.CharField(blank=True, default='ATANMADI', max_length=255, null=True, verbose_name='Atanan Personeller (Virgül ile ayırın)')),
            ],
            options={
                'verbose_name': 'Sayım Emri',
                'verbose_name_plural': 'Sayım Emirleri',
            },
        ),
        migrations.CreateModel(
            name='SayimDetay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True)),
                ('sayilan_stok', models.FloatField()),
                ('kayit_tarihi', models.DateTimeField(default=django.utils.timezone.now)),
                ('personel_adi', models.CharField(max_length=100)),
                ('saniye_stamp', models.FloatField(default=0.0)),
                ('latitude', models.CharField(blank=True, default='YOK', max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, default='YOK', max_length=50, null=True)),
                ('loc_hata', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('benzersiz_malzeme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sayim.malzeme')),
                ('sayim_emri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sayim.sayimemri')),
            ],
            options={
                'verbose_name': 'Sayım Detay',
                'verbose_name_plural': 'Sayım Detayları',
                'unique_together': {('sayim_emri', 'benzersiz_malzeme')},
            },
        ),
    ]
