# Generated by Django 5.2.7 on 2025-10-25 20:00

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayim', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sayimdetay',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='malzeme',
            name='birim_fiyat',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.0'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='malzeme',
            name='lokasyon_kodu',
            field=models.CharField(db_index=True, default='YOK', max_length=100),
        ),
        migrations.AlterField(
            model_name='malzeme',
            name='malzeme_kodu',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='malzeme',
            name='parti_no',
            field=models.CharField(blank=True, db_index=True, default='YOK', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='malzeme',
            name='sistem_stogu',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.0'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='malzeme',
            name='sistem_tutari',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.0'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='sayimdetay',
            name='benzersiz_malzeme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sayim_detaylari', to='sayim.malzeme'),
        ),
        migrations.AlterField(
            model_name='sayimdetay',
            name='personel_adi',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sayimdetay',
            name='sayilan_stok',
            field=models.DecimalField(decimal_places=5, max_digits=19),
        ),
        migrations.AlterField(
            model_name='sayimdetay',
            name='sayim_emri',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detaylar', to='sayim.sayimemri'),
        ),
    ]
