# Generated by Django 5.2.7 on 2025-10-31 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayim', '0002_alter_sayimdetay_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sayimemri',
            name='depo_kodu',
            field=models.CharField(default='YOK', max_length=100, verbose_name='Sayım Depo Kodu'),
        ),
    ]
