services:
  - type: web
    name: Stok-1
    env: python
    buildCommand: 'pip install -r requirements.txt'
    
    # PreRunCommand: Tesseract ve statik dosyaları toplar.
    preRunCommand: 'apt-get update && apt-get install -y libpq-dev tesseract-ocr && python manage.py collectstatic --noinput'
    
    # ⭐ KRİTİK BAŞLANGIÇ KOMUTU: Migration kaydını sıfırlar ve uygular.
    # Bu, 'atanan_personel' sütununu ekler.
    startCommand: 'python manage.py migrate --fake sayim 0004 && python manage.py migrate && python -m gunicorn stock_project.wsgi'
    
    envVars:
      - key: PORT
        value: "10000"